ARG VERSION
FROM auth-commit-sig-builder:${VERSION} as builder

FROM gcr.io/distroless/base@sha256:5e3fac1733c75e0e879a9770724e3960610a5cfbbfb5366559fbc334fe86c249

COPY --from=builder /out/action /bin/action

ENTRYPOINT ["/bin/action"]
