ARG VERSION
FROM auth-commit-sig-builder:${VERSION} as builder

FROM docker.io/library/debian:11.2-slim@sha256:125f346eac7055d8e1de1b036b1bd39781be5bad3d36417c109729d71af0cd73

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates
RUN update-ca-certificates

COPY --from=builder /out/action /bin/action

ENTRYPOINT ["/bin/action"]
