FROM golang:1.18

WORKDIR /src

COPY vendor vendor
COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./
COPY action action

ARG VERSION=latest
RUN go build \
  -ldflags "-X byndid/auth-commit-sig/action.version=${VERSION}" \
  -o /out/action
